image: tmaier/docker-compose:local

services:
  - docker:latest

workflow:
  rules:
  - if: '$CI_PIPELINE_SOURCE == "web"'
  - if: '$CI_COMMIT_TITLE =~ "^\#run_pipe"'

stages:
  - build-image
  - run

# Build an image
build-image-job:
  stage: build-image
  script:
    - docker build -f env/Dockerfile -t armann/the_benders_mouth:latest .

# Create a container and run
run-job:
  stage: run
  before_script:
    - docker stop the_benders_mouth || exit_code_delete=$?
    - docker rm the_benders_mouth || exit_code_delete=$?
  script:
    - docker-compose -f env/docker-compose.yml up -d --force-recreate
